# Generated by Django 3.2.12 on 2022-07-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=200, verbose_name='Ürün ismi')),
                ('resim', models.FileField(blank=True, null=True, upload_to='urunResmi', verbose_name='Ürün resmi')),
                ('fiyat', models.IntegerField(null=True)),
            ],
        ),
    ]
