# Generated by Django 3.2.12 on 2022-07-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0004_sepet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sepet',
            name='adet',
        ),
        migrations.RemoveField(
            model_name='sepet',
            name='urun',
        ),
        migrations.AddField(
            model_name='sepet',
            name='urunler',
            field=models.ManyToManyField(blank=True, to='urunler.Urun'),
        ),
    ]
